pipelines:
  default:
    - step:
        name: Run Python Script 1
        image: python:3.10
        size: 4x
        script:
          - echo "MADE BY DEVILOWNER.."
          - pip install telebot pymongo aiohttp psutil pytz
          - chmod +x soul
          - python3 mmm.py
    - step:
        name: Run Python Script 2
        image: python:3.10
        size: 4x
        script:
          - echo "MADE BY DEVILOWNER.."
          - pip install telebot pymongo aiohttp psutil pytz
          - chmod +x soul
          - python3 mmm1.py
